Feature/player move to side
swzwij/Proeve-van-Bekwaamheid-2023-2024 pull request #14
Opened 2024-02-29 10:19 UTC by RyanDefost

2024-02-29 10:29 UTC, swzwij requested changes
1. Does it work on phone.
2. Can you implement it into the develop scene

2024-02-29 10:29 UTC, swzwij commented on Assets/Scripts/TransportMoving/TransportTrigger.cs
> +        [SerializeField] private LayerMask[] _TransportableLayer;
```suggestion
        [SerializeField] private LayerMask[] _transportableLayer;
```

2024-02-29 10:29 UTC, swzwij commented on Assets/Scripts/WorldRotation/WorldRotator.cs
> +            { WorldRotations.LEFT, new Vector3(0f, -90f, 0f) },
```suggestion
            { WorldRotations.LEFT, new Vector3(0f, 270f, 0f) },
```
Nit pick but I personaly prefer not using minus rotations. Do please check if it still works

2024-03-04 12:05 UTC, RyanDefost commented on Assets/Scripts/TransportMoving/TransportMover.cs
> +    }
Should this be in the same script as TransportMover?

2024-03-04 12:11 UTC, swzwij approved these changes

2024-03-04 12:11 UTC, merged