Feature/world rotation
swzwij/Proeve-van-Bekwaamheid-2023-2024 pull request #2
Opened 2024-02-15 10:25 UTC by RyanDefost

2024-02-15 10:26 UTC, RyanDefost commented
code is done, still need to add GameObject stuff

2024-02-15 13:56 UTC, swzwij requested changes

2024-02-15 13:56 UTC, swzwij commented on Assets/Scenes/SampleScene.unity
Maybe rename it to "levelRotation" or something along those lines.

2024-02-15 13:56 UTC, swzwij commented on Assets/Scenes/SampleScene.unity
I now see the other scene. Maybe just delete this one.

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/Materials/Screenshot 2024-02-14 151129.mat
Why is there a Material folder in the scripts folder containing a material with a name which doesn't follow the naming conventions.

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
Please put it in a folder instead of straight in the `Scripts` folder

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +namespace UntitledCube
Remember to change the namespace when putting it in a folder

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +    public enum RotationDirection
I'd put this in its own script for clarity and that way it can also be used in other classes if needed.

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        private float _timebetweenRotations = 2f;
```suggestion
        [SerializeField] private List<RotationDirection> _rotationDiractions = new();
        [SerializeField] private float _timebetweenRotations = 2f;
```

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        private float _stepSpeed = 0.05f;
```suggestion
        [SerializeField] private float _stepAmount = 20;
        [SerializeField] private float _stepSpeed = 0.05f;
```

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        private Dictionary<RotationDirection, Vector3> directions = new Dictionary<RotationDirection, Vector3>();
```suggestion
        private Dictionary<RotationDirection, Vector3> _directions = new();
```

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        private Vector3 currentRotation;
```suggestion
        private Vector3 _currentRotation;
```

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        IEnumerator RotatingSides()
Missing access modifier

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +            foreach (var rotation in _rotationDiractions)
Please use a explicit type instead of var

2024-02-15 13:56 UTC, swzwij commented on Assets/Scripts/WorldRotator.cs
> +        IEnumerator RotationSteps(Vector3 step)
Missing access modifier

2024-02-15 14:18 UTC, swzwij requested changes

2024-02-15 14:18 UTC, swzwij commented on Assets/Scripts/WorldRotation/WorldRotator.cs
> +        private Dictionary<RotationDirection, Vector3> directions = new();
```suggestion
        private Dictionary<RotationDirection, Vector3> _directions = new();
```

2024-02-16 10:47 UTC, swzwij requested changes
- On phone the cube does not stay on a 90 degree axis
- There is a noticeable difference between phone and PC's framerates

2024-02-27 13:19 UTC, swzwij requested changes

2024-02-27 13:19 UTC, swzwij commented on Assets/Scripts/WorldRotation/WorldRotator.cs
> +        private Dictionary<RotationDirection, Vector3> _directions = new();
```suggestion
        private Dictionary<RotationDirection, Vector3> _directions = new Dictionary<RotationDirection, Vector3>()
        {
            { RotationDirection.UP, new Vector3(-90f, 0f, 0f) },
            { RotationDirection.DOWN, new Vector3(90f, 0f, 0f) },
            { RotationDirection.LEFT, new Vector3(0f, 90f, 0f) },
            { RotationDirection.RIGHT, new Vector3(0f, -90f, 0f) }
        };
```
Please fact check values before adding the suggestion

2024-02-27 13:19 UTC, swzwij commented on Assets/Scripts/WorldRotation/WorldRotator.cs
> +        }
Can be removed if its already in the dictonary

2024-02-27 13:19 UTC, swzwij commented on Assets/Scripts/WorldRotation/WorldRotator.cs
> +        private void Awake() => SetValues();
Can be removed if its already in the dictonary

2024-02-28 12:50 UTC, swzwij submitted a review, later dismissed

2024-02-28 12:53 UTC, swzwij approved these changes

2024-02-28 12:53 UTC, merged