Feature/pause menu
swzwij/Proeve-van-Bekwaamheid-2023-2024 pull request #24
Opened 2024-03-07 09:31 UTC by Minoord

#What Changed:
Added a pause button, that goes to the pause state and pauses the menu

#How to Test:
Build the game and click on the pause button. the game should freeze and you can only interact with UI

2024-03-07 12:26 UTC, swzwij requested changes

2024-03-07 12:26 UTC, swzwij commented on Assets/Scripts/Input/InputSystem.cs
> +        }
```suggestion
        public static void ToggleAllInputs(bool isActive) 
            => _subscribedInputs.Values.ToList().ForEach(action => isActive ? action.Enable() : action.Disable());

```

2024-03-07 12:26 UTC, swzwij commented on Assets/Scripts/Input/InputSystem.cs
>          private static InputActions _inputAction = new();
```suggestion
        private static readonly InputActions _inputAction = new();
```

2024-03-07 12:26 UTC, swzwij commented on Assets/Scripts/Input/InputSystem.cs
>          private static Dictionary<System.Action<InputAction.CallbackContext>, InputAction> _subscribedInputs = new();
```suggestion
        private static readonly Dictionary<System.Action<InputAction.CallbackContext>, InputAction> _subscribedInputs = new();
```

2024-03-07 12:26 UTC, swzwij commented on Assets/Scripts/Input/InputSystem.cs
>          private static Dictionary<System.Action<InputAction.CallbackContext>, InputAction> _subscribedInputs = new();
Instead of putting `System` in front of the action you can make use of the `System` library at the top of the script (`using System;`)

2024-03-07 13:45 UTC, Minoord commented on Assets/Scripts/Input/InputSystem.cs
> +        }
![image](https://github.com/swzwij/Proeve-van-Bekwaamheid-2023-2024/assets/70703952/ab8d7362-b9cb-4dbd-b2b6-77d5c09df75e)
:(

2024-03-07 14:11 UTC, swzwij requested changes

2024-03-07 14:11 UTC, swzwij commented on Assets/Scripts/Input/InputSystem.cs
> +        }
I gave up, leave it.

2024-03-07 14:11 UTC, swzwij commented on Assets/Scripts/UI/Buttons/PauseButton.cs
> +        }
```suggestion
private void TogglePauseState() 
{
    GameStateMachine.Instance.CurrentState is PausedState ? 
        GameStateMachine.Instance.MoveToNextState() : 
        GameStateMachine.Instance.SetState<PausedState>(); 
}
```

2024-03-07 14:11 UTC, swzwij commented on Assets/Scripts/UI/Buttons/PauseButton.cs
> +        }
Can be one liner

2024-03-11 08:49 UTC, swzwij approved these changes

2024-03-11 08:56 UTC, merged