Feature/maze generation
swzwij/Proeve-van-Bekwaamheid-2023-2024 pull request #7
Opened 2024-02-26 14:34 UTC by swzwij

2024-02-27 10:00 UTC, Minoord commented on Assets/Scripts/Maze/Generation/MazeGenerator.cs
> +        private static readonly List<string> _fullSeed = new();
I want to get the current seed!

2024-02-27 13:23 UTC, BNS-MarkUlrich requested changes

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on Assets/Adaptive Performance.meta
Do we want to avoid spaces in folder names?

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on Assets/Scripts/Maze/Cells/MazeCell.cs
> +        public bool Start
I think it improves readability if you write bools as verbs. Aka `IsStart`, `CanStart`, etc

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on Assets/Scripts/Maze/Cells/MazeCell.cs
> +        public bool End
I think it improves readability if you write bools as verbs. Aka `IsEnd`, `CanEnd`, etc

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on Assets/Scripts/Maze/Generation/LevelShowCase.cs
Can this be removed now? I don't mind if it stays (for the main menu, for example) but if it does, `rotate` should be renamed to a verb.

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on Assets/Scripts/Maze/Generation/MazeGeneratorDebug.cs
This can go

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on ProjectSettings/EditorBuildSettings.asset
Please restore this to the version from develop.

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
Please restore this to the version from develop.

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on ProjectSettings/ProjectSettings.asset
Please restore this to the version from develop.

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on ProjectSettings/SceneTemplateSettings.json
Please restore this to the version from develop.

2024-02-27 13:23 UTC, BNS-MarkUlrich commented on ProjectSettings/TimelineSettings.asset
Please restore this to the version from develop.

2024-02-28 09:52 UTC, BNS-MarkUlrich approved these changes, later dismissed

2024-02-28 12:34 UTC, merged